name: Scrape DeFi Hourly

on:
  schedule:
    - cron: '0 * * * *' # every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scrape-ux-hourly
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          DEBUG_SCRAPE: '1'
        run: |
          npm run scrape:ux
          npm run scrape:shade:lend
          npm run scrape:shade:borrow

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add public/data/*.json
            git commit -m "chore: update DeFi snapshots [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
